/**
 * Generates every app icon in public/ from the one geometry table below.
 * Run with `npm run icons` after changing anything here.
 *
 * Why generate rather than hand-write: the manifest needs PNGs, not just SVG.
 * Chrome/Android builds a real installed app (a WebAPK) from raster manifest
 * icons, and iOS only ever looks at the PNG in `<link rel="apple-touch-icon">`.
 * That's five rasters plus three SVGs of the same barbell, and eight hand-kept
 * copies of one drawing drift. So the drawing lives here once and everything
 * else falls out of it.
 *
 * There's no image library in this project's dependency tree and the artwork is
 * nine round-capped straight lines, so the rasterizer is a distance field: for
 * each pixel, the distance to the nearest line gives an exactly round cap and a
 * one-pixel antialiased edge for free. PNG encoding is node's own zlib.
 */
import { deflateSync } from 'node:zlib'
import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const OUT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'public')

// --- the drawing ---------------------------------------------------------

// A barbell seen side-on: the bar, three plates per side that step taller
// towards the middle, and a stub of bar poking out past the outermost plate.
// Coordinates are traced from the reference artwork and are only ever relative
// to (CX, CY) and to each other — SCALE below sets the actual size.
const CX = 90
const CY = 52

// Listed for the left side only; the right side is generated as a mirror, so the
// two halves cannot drift.
const LEFT = [
  [25.5, 52, 28.5, 52], // bar end, poking out past the plates
  [36, 34.5, 36, 69.5], // outer plate — shortest
  [48, 30.5, 48, 73.5], // middle plate
  [61, 26.5, 61, 77.5], // inner plate — tallest
]
// The bar spans the middle and is its own mirror, so it sits outside LEFT.
const BAR = [68.5, 52, 111.5, 52]

const SEGMENTS = [
  BAR,
  ...LEFT,
  ...LEFT.map(([x1, y1, x2, y2]) => [2 * CX - x1, y1, 2 * CX - x2, y2]),
]

// --- layout --------------------------------------------------------------

const SIZE = 512 // design space; every output is a scaling of this
const BG = [0x0a, 0x0a, 0x0a] // matches --color-bg and the manifest theme_color
const FG = [0xff, 0xff, 0xff]

/**
 * Two cuts of the same drawing.
 *
 * `app` is the real icon. Its stroke is deliberately heavier than the reference
 * artwork's: scaled faithfully the lines would land under a pixel wide in a
 * launcher grid and wash out. 14 is the heaviest the drawing takes before the
 * gaps between the plates start closing up.
 *
 * `favicon` is a browser-tab cut at 16–32px, where the `app` weight disappears
 * entirely. Bolder and slightly larger; three plates a side is already more
 * detail than 16px can hold, so this is as far as it goes.
 */
const CUTS = {
  app: { scale: 2.9, stroke: 14 },
  favicon: { scale: 3.0, stroke: 20 },
}

// Rounded-square corner, for the icon that is NOT handed to a launcher mask.
const RADIUS = 112

/** Source coordinates → design space. */
const tx = (x, cut) => SIZE / 2 + (x - CX) * cut.scale
const ty = (y, cut) => SIZE / 2 + (y - CY) * cut.scale

// --- SVG -----------------------------------------------------------------

const round = (n) => String(Math.round(n * 10) / 10)
const hex = ([r, g, b]) => `#${[r, g, b].map((c) => c.toString(16).padStart(2, '0')).join('')}`

function svg({ cut, radius, note }) {
  const lines = SEGMENTS.map(
    ([x1, y1, x2, y2]) =>
      `    <line x1="${round(tx(x1, cut))}" y1="${round(ty(y1, cut))}" ` +
      `x2="${round(tx(x2, cut))}" y2="${round(ty(y2, cut))}"/>`,
  ).join('\n')
  return `<!-- Generated by scripts/make-icons.mjs — edit that, not this.
     ${note} -->
<svg xmlns="http://www.w3.org/2000/svg" width="${SIZE}" height="${SIZE}" viewBox="0 0 ${SIZE} ${SIZE}">
  <rect width="${SIZE}" height="${SIZE}"${radius ? ` rx="${radius}"` : ''} fill="${hex(BG)}"/>
  <g fill="none" stroke="${hex(FG)}" stroke-width="${cut.stroke}" stroke-linecap="round">
${lines}
  </g>
</svg>
`
}

// --- raster --------------------------------------------------------------

const clamp01 = (n) => (n < 0 ? 0 : n > 1 ? 1 : n)

/** Distance from (px, py) to a line segment — the capsule's centreline. */
function distToSegment(px, py, [x1, y1, x2, y2]) {
  const dx = x2 - x1
  const dy = y2 - y1
  const len2 = dx * dx + dy * dy
  const t = len2 === 0 ? 0 : clamp01(((px - x1) * dx + (py - y1) * dy) / len2)
  return Math.hypot(px - (x1 + t * dx), py - (y1 + t * dy))
}

/** Signed distance to the rounded-square background: negative inside. */
function distToRoundedSquare(px, py, radius) {
  const inset = SIZE / 2 - radius
  const qx = Math.abs(px - SIZE / 2) - inset
  const qy = Math.abs(py - SIZE / 2) - inset
  return Math.hypot(Math.max(qx, 0), Math.max(qy, 0)) - radius
}

/**
 * Renders RGBA pixels at `size`. Coverage comes from the distance fields: a
 * pixel whose centre sits exactly on an edge gets 0.5, ramping to solid one
 * pixel inside — which is the antialiasing.
 */
function raster(size, { cut, radius }) {
  const unit = SIZE / size // design units per output pixel
  const px = Buffer.alloc(size * size * 4)
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      // Sample at the pixel's centre, in design space.
      const sx = (x + 0.5) * unit
      const sy = (y + 0.5) * unit

      let nearest = Infinity
      for (const seg of SEGMENTS) {
        const d = distToSegment(sx, sy, [
          tx(seg[0], cut),
          ty(seg[1], cut),
          tx(seg[2], cut),
          ty(seg[3], cut),
        ])
        if (d < nearest) nearest = d
      }
      const ink = clamp01(0.5 + (cut.stroke / 2 - nearest) / unit)
      // A maskable icon has no corners of its own, so it is opaque everywhere.
      const alpha = radius ? clamp01(0.5 - distToRoundedSquare(sx, sy, radius) / unit) : 1

      const i = (y * size + x) * 4
      for (let c = 0; c < 3; c++) px[i + c] = Math.round(BG[c] + (FG[c] - BG[c]) * ink)
      px[i + 3] = Math.round(alpha * 255)
    }
  }
  return px
}

// --- PNG -----------------------------------------------------------------

const CRC_TABLE = Uint32Array.from({ length: 256 }, (_, n) => {
  let c = n
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1
  return c >>> 0
})

function crc32(buf) {
  let c = 0xffffffff
  for (const byte of buf) c = CRC_TABLE[(c ^ byte) & 0xff] ^ (c >>> 8)
  return (c ^ 0xffffffff) >>> 0
}

function chunk(type, data) {
  const head = Buffer.alloc(8)
  head.writeUInt32BE(data.length, 0)
  head.write(type, 4, 'ascii')
  const crc = Buffer.alloc(4)
  crc.writeUInt32BE(crc32(Buffer.concat([head.subarray(4), data])), 0)
  return Buffer.concat([head, data, crc])
}

/** 8-bit RGBA PNG. Filter type 0 on every scanline — zlib does the work. */
function png(size, pixels) {
  const stride = size * 4
  const raw = Buffer.alloc((stride + 1) * size)
  for (let y = 0; y < size; y++) {
    pixels.copy(raw, y * (stride + 1) + 1, y * stride, (y + 1) * stride)
  }
  const ihdr = Buffer.alloc(13)
  ihdr.writeUInt32BE(size, 0)
  ihdr.writeUInt32BE(size, 4)
  ihdr[8] = 8 // bit depth
  ihdr[9] = 6 // colour type: truecolour with alpha
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ])
}

// --- outputs -------------------------------------------------------------

const app = CUTS.app
const rounded = { cut: app, radius: RADIUS }
const bleed = { cut: app, radius: 0 }

const FILES = [
  // The SVGs stay for anything that prefers vector — a desktop browser tab, and
  // the manifest's `any` fallback.
  [
    'icon.svg',
    svg({ ...rounded, note: 'The app icon. Rounded corners of its own, so it is the "any" icon.' }),
  ],
  [
    'icon-maskable.svg',
    svg({
      ...bleed,
      note:
        "Full-bleed variant. Android crops a maskable icon to the launcher's own\n     shape and keeps only what lands inside, which would show straight through\n     icon.svg's transparent corners as pale notches. The barbell itself sits\n     inside the 80%-diameter safe circle either way, so it is unchanged.",
    }),
  ],
  [
    'favicon.svg',
    svg({ cut: CUTS.favicon, radius: RADIUS, note: 'Bolder cut for a 16–32px browser tab.' }),
  ],

  // What actually gets installed. Chrome/Android reads 192 and 512 from the
  // manifest; iOS reads only icon-180.png, via the link tag in index.html.
  ['icon-180.png', png(180, raster(180, bleed))], // iOS applies its own mask
  ['icon-192.png', png(192, raster(192, rounded))],
  ['icon-512.png', png(512, raster(512, rounded))],
  ['icon-maskable-192.png', png(192, raster(192, bleed))],
  ['icon-maskable-512.png', png(512, raster(512, bleed))],
]

for (const [name, data] of FILES) {
  await writeFile(path.join(OUT, name), data)
  console.log(`  public/${name}`)
}
